defaults: &default
  s3_access_key_id: AKIAIZSRFLA67FFN7ZTQ
  s3_secret_access_key: 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
  s3_region: us-east-2

development:
  <<: *default
  secret_key_base: 6bb1a2f50babb8def7d57ee596bf2336f7a708dad6978efe4608d9cb4d6036f45bde7be02c38092129d79ebb0892fffe07d6a020da6c93c2576ecc7f560ac102
  
  host: localhost:3000
  mailgun_api_key: 
  mailgun_domain: .mailgun.org

  s3_bucket: turnstr-development
  s3_host_name: s3.us-west-2.amazonaws.com
  firebase_server_api_key: AAAA8RDsLvc:APA91bEaDPTpc5jNOEOQbz8jjPaBA2_sgzsXK-XzJbffSmayzutm49ztX2Sh70ndF1Q5TINT0Dcxo14jF4Rub32BqAC9aaKtte1UToeTHCDXlbCMUQ_vlIzCzo4MnXu8FFrUo8D_undf

staging:
  <<: *default
  secret_key_base: 6bb1a2f50babb8def7d57ee596bf2336f7a708dad6978efe4608d9cb4d6036f45bde7be02c38092129d79ebb0892fffe07d6a020da6c93c2576ecc7f560ac102
  host: fathomless-retreat-45620.herokuapp.com
  mailgun_api_key: 
  mailgun_domain: .mailgun.org

  s3_access_key_id: AKIAIZSRFLA67FFN7ZTQ
  s3_secret_access_key: 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
  s3_region: us-west-2

  s3_bucket: turnstr-staging
  s3_host_name: s3.us-west-2.amazonaws.com
  firebase_server_api_key: AAAA8RDsLvc:APA91bEaDPTpc5jNOEOQbz8jjPaBA2_sgzsXK-XzJbffSmayzutm49ztX2Sh70ndF1Q5TINT0Dcxo14jF4Rub32BqAC9aaKtte1UToeTHCDXlbCMUQ_vlIzCzo4MnXu8FFrUo8D_undf

production:
  <<: *default
  secret_key_base: 1b1b03ecb424b895f11b36af8ce9bb55b7c76867fb1454026f31ff6e5a1f5ae81aadc37bcdf8b34ca1dae88b1f96d8e04ce5b51eea796d4c7a2dd56ee522068c
  host: http://18.217.214.170
  mailgun_api_key:
  mailgun_domain: .mailgun.org

  s3_access_key_id: AKIAIZSRFLA67FFN7ZTQ
  s3_secret_access_key: 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
  s3_region: us-east-2

  s3_bucket: turnstr-production
  s3_host_name: s3.us-west-2.amazonaws.com

  firebase_server_api_key: AAAA8RDsLvc:APA91bEaDPTpc5jNOEOQbz8jjPaBA2_sgzsXK-XzJbffSmayzutm49ztX2Sh70ndF1Q5TINT0Dcxo14jF4Rub32BqAC9aaKtte1UToeTHCDXlbCMUQ_vlIzCzo4MnXu8FFrUo8D_undf

