defaults: &default
  s3_access_key_id: AKIAILFC4IUANKGNBDZA
  s3_secret_access_key: 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
  s3_region: ap-south-1

development:
  <<: *default
  secret_key_base: 6bb1a2f50babb8def7d57ee596bf2336f7a708dad6978efe4608d9cb4d6036f45bde7be02c38092129d79ebb0892fffe07d6a020da6c93c2576ecc7f560ac102
  frotend_app_url: http://localhost:3000

  host: localhost:3000
  mailgun_api_key: 
  mailgun_domain: .mailgun.org

  s3_bucket: turnstr2-development
  s3_host_name: s3.ap-south-1.amazonaws.com